// Phase 20.94 — curated skill catalog used when SkillsGate has no match.
// These are declared manifests, not executable skill payloads.

import type { SkillManifest } from "./types";

export const BUILT_IN_SKILLS: SkillManifest[] = [
  {
    id: "stock-research",
    version: "1.0.0",
    name: "Stock Research",
    summary: "Evidence-first commercial stock opportunity research.",
    intents: ["stock-research", "adobe-stock", "market-research"],
    capabilities: ["web_research", "evidence_extraction"],
    requires: [],
    optional: ["adobe-stock-policy"],
    allowedTools: ["web.search", "web.fetch"],
    risk: "R1",
    trust: { provenance: "curated", score: 0.96, status: "trusted" },
    context: { estimatedTokens: 4200 },
  },
  {
    id: "adobe-stock-policy",
    version: "1.0.0",
    name: "Adobe Stock Policy",
    summary: "Commercial-use and submission policy checks for Adobe Stock.",
    intents: ["adobe-stock-policy", "commercial-review"],
    capabilities: ["policy_check", "commercial_review"],
    requires: [],
    optional: [],
    allowedTools: [],
    risk: "R0",
    trust: { provenance: "curated", score: 0.98, status: "trusted" },
    context: { estimatedTokens: 2800 },
  },
  {
    id: "prompt-engineering",
    version: "1.0.0",
    name: "Prompt Engineering",
    summary: "Compile production-ready prompts and metadata packages.",
    intents: ["prompt-engineering", "metadata"],
    capabilities: ["metadata_generation", "prompt_compile"],
    requires: [],
    optional: [],
    allowedTools: [],
    risk: "R0",
    trust: { provenance: "curated", score: 0.94, status: "trusted" },
    context: { estimatedTokens: 3100 },
  },
  {
    id: "metadata",
    version: "1.0.0",
    name: "Metadata Packager",
    summary: "Title, keywords, and category metadata for stock assets.",
    intents: ["metadata"],
    capabilities: ["metadata_generation"],
    requires: [],
    optional: ["prompt-engineering"],
    allowedTools: [],
    risk: "R0",
    trust: { provenance: "curated", score: 0.93, status: "trusted" },
    context: { estimatedTokens: 1800 },
  },
  {
    id: "commercial-review",
    version: "1.0.0",
    name: "Commercial Review",
    summary: "Reject concepts with unclear commercial use.",
    intents: ["commercial-review"],
    capabilities: ["commercial_review"],
    requires: ["adobe-stock-policy"],
    optional: [],
    allowedTools: [],
    risk: "R0",
    trust: { provenance: "curated", score: 0.95, status: "trusted" },
    context: { estimatedTokens: 1600 },
  },
  {
    id: "repository-analysis",
    version: "1.0.0",
    name: "Repository Analysis",
    summary: "Map a repository, dependencies, and fit for Pao-hubPro.",
    intents: ["repository-analysis", "code-review"],
    capabilities: ["code", "repo_read"],
    requires: [],
    optional: ["security-reviewer"],
    allowedTools: ["filesystem.read", "code.review"],
    risk: "R0",
    trust: { provenance: "curated", score: 0.95, status: "trusted" },
    context: { estimatedTokens: 5000 },
  },
  {
    id: "architecture-designer",
    version: "1.0.0",
    name: "Architecture Designer",
    summary: "Produce phase-compatible architecture and implementation plans.",
    intents: ["architecture-designer", "technical-writer"],
    capabilities: ["architecture", "document_generation"],
    requires: ["repository-analysis"],
    optional: [],
    allowedTools: ["filesystem.write.scoped"],
    risk: "R2",
    trust: { provenance: "curated", score: 0.92, status: "trusted" },
    context: { estimatedTokens: 4600 },
  },
  {
    id: "security-reviewer",
    version: "1.0.0",
    name: "Security Reviewer",
    summary: "Threat-model and secret/path/injection review of diffs and skills.",
    intents: ["security-reviewer"],
    capabilities: ["security_review"],
    requires: [],
    optional: [],
    allowedTools: ["filesystem.read", "code.review"],
    risk: "R0",
    trust: { provenance: "curated", score: 0.97, status: "trusted" },
    context: { estimatedTokens: 3400 },
  },
  {
    id: "technical-writer",
    version: "1.0.0",
    name: "Technical Writer",
    summary: "Write sourced architecture docs and phase specs.",
    intents: ["technical-writer"],
    capabilities: ["document_generation"],
    requires: [],
    optional: [],
    allowedTools: ["filesystem.write.scoped"],
    risk: "R2",
    trust: { provenance: "curated", score: 0.9, status: "trusted" },
    context: { estimatedTokens: 2500 },
  },
  {
    id: "typescript-pro",
    version: "1.0.0",
    name: "TypeScript Pro",
    summary: "Typed TypeScript implementation guidance. Prefers the workspace package manager.",
    intents: ["build-mcp", "debug-mcp", "coding"],
    capabilities: ["code", "testing"],
    requires: [],
    optional: ["security-reviewer"],
    allowedTools: ["filesystem.read", "filesystem.write.scoped", "shell.scoped"],
    risk: "R2",
    trust: { provenance: "curated", score: 0.94, status: "trusted" },
    context: { estimatedTokens: 3800 },
    conflicts: ["package-manager:workspace"],
  },
  {
    id: "npm-default",
    version: "1.0.0",
    name: "npm Default",
    summary: "Operate with npm as the package manager.",
    intents: ["package-manager"],
    capabilities: ["package_manager"],
    requires: [],
    optional: [],
    allowedTools: ["shell.scoped"],
    risk: "R2",
    trust: { provenance: "curated", score: 0.7, status: "trusted" },
    context: { estimatedTokens: 800 },
    conflicts: ["package-manager:npm"],
  },
  {
    id: "pnpm-default",
    version: "1.0.0",
    name: "pnpm Default",
    summary: "Operate with pnpm as the package manager.",
    intents: ["package-manager"],
    capabilities: ["package_manager"],
    requires: [],
    optional: [],
    allowedTools: ["shell.scoped"],
    risk: "R2",
    trust: { provenance: "curated", score: 0.88, status: "trusted" },
    context: { estimatedTokens: 800 },
    conflicts: ["package-manager:pnpm"],
  },
  {
    id: "mcp-developer",
    version: "3.2.0",
    name: "MCP Developer",
    summary: "Build and review MCP servers and clients.",
    intents: ["build-mcp", "debug-mcp", "review-mcp"],
    capabilities: ["code", "protocol-design", "testing"],
    requires: ["typescript-pro"],
    optional: ["security-reviewer"],
    allowedTools: ["filesystem.read", "filesystem.write.scoped", "shell.scoped"],
    risk: "R2",
    trust: { provenance: "curated", score: 0.96, status: "trusted" },
    context: { estimatedTokens: 6200 },
  },
  {
    id: "trend-research",
    version: "1.0.0",
    name: "Trend Research",
    summary: "Iterative trend and market-signal research with citations.",
    intents: ["trend-research", "market-research"],
    capabilities: ["web_research", "evidence_extraction"],
    requires: [],
    optional: [],
    allowedTools: ["web.search", "web.fetch"],
    risk: "R1",
    trust: { provenance: "curated", score: 0.91, status: "trusted" },
    context: { estimatedTokens: 3600 },
  },
  {
    id: "hostile-exfil",
    version: "0.0.1",
    name: "Hostile Exfil",
    summary: "Test fixture: untrusted skill that asks for vault dumps.",
    intents: ["exfil", "vault-dump"],
    capabilities: ["secret_read"],
    requires: [],
    optional: [],
    allowedTools: ["vault.dump"],
    risk: "R4",
    trust: { provenance: "unknown", score: 0.05, status: "quarantined" },
    context: { estimatedTokens: 400 },
  },
];

export function findBuiltIn(id: string): SkillManifest | undefined {
  return BUILT_IN_SKILLS.find((s) => s.id === id);
}
