// Phase 20.24 — Pao-hubPro × OmniGet Local Media Acquisition & MCP Engine
// Core Type Definitions

export type ProviderName = "omniget" | "ytdlp" | "native" | string;

export type MediaType = "video" | "audio" | "image" | "gallery" | "document" | "unknown";

export type DownloadPreset = "best" | "video" | "audio" | "reference" | "transcript";

export type JobPriority = "P0" | "P1" | "P2" | "P3";

export type JobStatus =
  | "queued"
  | "validating"
  | "running"
  | "processing"
  | "retry_wait"
  | "completed"
  | "failed"
  | "cancelled"
  | "blocked";

export type UsageClass = "research_reference" | "internal_training" | "concept_analysis" | "production_derivative";

export type PermissionTier = 0 | 1 | 2 | 3 | 4;

export interface ProviderCapability {
  formats: string[];
  supportsSubtitles: boolean;
  supportsAudioExtraction: boolean;
  supportsBatch: boolean;
  supportsThumbnails: boolean;
  maxResolution?: string;
  notes?: string;
}

export interface ProviderHealth {
  provider: ProviderName;
  status: "healthy" | "degraded" | "offline";
  available: boolean;
  version?: string;
  binaryPath?: string;
  lastCheckedAt: string;
  latencyMs?: number;
  capabilities: ProviderCapability;
  errorMessage?: string;
}

export interface MediaFormat {
  formatId: string;
  ext: string;
  resolution?: string;
  width?: number;
  height?: number;
  filesizeApprox?: number;
  fps?: number;
  vcodec?: string;
  acodec?: string;
  qualityNote?: string;
}

export interface MediaSubtitle {
  language: string;
  ext: string;
  url?: string;
  isAutoGenerated?: boolean;
}

export interface InspectRequest {
  url: string;
  preferredProvider?: ProviderName;
  secretRef?: string;
}

export interface InspectResult {
  provider: ProviderName;
  url: string;
  normalizedUrl: string;
  title: string;
  description?: string;
  mediaType: MediaType;
  durationSec?: number;
  thumbnailUrl?: string;
  formats: MediaFormat[];
  subtitles: MediaSubtitle[];
  author?: string;
  sourcePlatform: string;
  requiresAuth: boolean;
  supported: boolean;
  inspectedAt: string;
}

export interface DownloadRequest {
  url: string;
  preset?: DownloadPreset;
  priority?: JobPriority;
  customFormat?: string;
  extractAudio?: boolean;
  extractTranscript?: boolean;
  generateThumbnail?: boolean;
  usageClass?: UsageClass;
  requestedBy?: string;
  secretRef?: string;
  notes?: string;
}

export interface MediaJob {
  id: string;
  type: "download" | "batch" | "process" | "transcribe";
  provider: ProviderName;
  sourceUrl: string;
  normalizedUrl: string;
  status: JobStatus;
  priority: JobPriority;
  preset: DownloadPreset;
  progressPercent: number;
  downloadSpeedBytesSec?: number;
  etaSeconds?: number;
  downloadedBytes?: number;
  totalBytes?: number;
  outputPath?: string;
  outputArtifactId?: string;
  retryCount: number;
  maxRetries: number;
  requestedBy: string;
  usageClass: UsageClass;
  exportToStockAllowed: boolean;
  createdAt: string;
  startedAt?: string;
  finishedAt?: string;
  errorCode?: string;
  errorMessage?: string;
}

export interface BatchDownloadRequest {
  urls: string[];
  preset?: DownloadPreset;
  priority?: JobPriority;
  requestedBy?: string;
}

export interface BatchDownloadResult {
  batchId: string;
  totalUrls: number;
  jobIds: string[];
}

export interface MediaArtifact {
  artifactId: string;
  jobId: string;
  type: MediaType;
  sourceUrl: string;
  sourcePlatform: string;
  title: string;
  localPath: string;
  filename: string;
  sha256: string;
  mimeType: string;
  sizeBytes: number;
  durationSec?: number;
  width?: number;
  height?: number;
  thumbnailPath?: string;
  transcriptPath?: string;
  usageClass: UsageClass;
  exportToStock: boolean;
  createdAt: string;
  derivedFromArtifactId?: string;
}

export interface MediaProvenance {
  sourceUrl: string;
  sourcePlatform: string;
  acquisitionTime: string;
  provider: ProviderName;
  originalFilename?: string;
  sha256: string;
  processingSteps: string[];
  notes?: string;
}

export interface MediaProcessRequest {
  sourceArtifactId: string;
  targetPreset: "web_preview" | "audio_wav" | "audio_mp3" | "thumbnail_1080" | "video_h264" | "video_h265";
  requestedBy?: string;
}

export interface TranscribeRequest {
  sourceArtifactId: string;
  language?: string;
  modelSize?: "tiny" | "base" | "small" | "medium";
}

export interface TranscriptResult {
  artifactId: string;
  language: string;
  durationSec: number;
  text: string;
  segments: Array<{
    start: number;
    end: number;
    text: string;
  }>;
}

export interface MediaProvider {
  readonly name: ProviderName;
  inspect(request: InspectRequest): Promise<InspectResult>;
  download(job: MediaJob, onProgress?: (progress: Partial<MediaJob>) => void): Promise<{ outputPath: string; metadata?: Record<string, unknown> }>;
  cancel(jobId: string): Promise<void>;
  getStatus(jobId: string): Promise<JobStatus>;
  healthCheck(): Promise<ProviderHealth>;
}

export interface MediaStorageLayout {
  rootDir: string;
  incomingDir: string;
  jobsDir: string;
  cacheDir: string;
  tempDir: string;
  referencesDir: string;
  transcriptsDir: string;
  thumbnailsDir: string;
  processedDir: string;
}

export interface SecretReference {
  refId: string;
  category: "browser_cookie" | "api_key" | "proxy" | "auth_token";
  label: string;
  domain?: string;
  createdAt: string;
  expiresAt?: string;
}

export interface BridgePairingRequest {
  extensionId: string;
  extensionVersion: string;
  clientNonce: string;
  timestamp: number;
}

export interface BridgePairingResponse {
  installationToken: string;
  sessionToken: string;
  serverNonce: string;
  expiresAtMs: number;
}

export interface BridgeDispatchRequest {
  action: "inspect" | "download" | "extract_audio" | "transcribe" | "add_queue";
  url: string;
  preset?: DownloadPreset;
  extensionId: string;
  sessionToken: string;
  timestamp: number;
  signature: string;
}
