// Phase 20.24 — Pao-hubPro × OmniGet Local Media Acquisition & MCP Engine
// yt-dlp Fallback Provider Adapter

import type {
  MediaProvider,
  InspectRequest,
  InspectResult,
  MediaJob,
  JobStatus,
  ProviderHealth,
  MediaFormat,
  MediaSubtitle,
} from "./types";
import { runProcessSafely } from "./process-runner";
import { validateAndNormalizeUrl } from "./url-policy";
import { MediaError } from "./errors";

export class YtDlpAdapter implements MediaProvider {
  readonly name = "ytdlp";
  private binaryName = process.platform === "win32" ? "yt-dlp.exe" : "yt-dlp";
  private activeJobs = new Map<string, { abort: () => void }>();

  async healthCheck(): Promise<ProviderHealth> {
    const startTime = Date.now();
    try {
      const res = await runProcessSafely({
        binary: this.binaryName,
        args: ["--version"],
        timeoutMs: 5000,
      });

      const latencyMs = Date.now() - startTime;
      if (res.exitCode === 0) {
        return {
          provider: this.name,
          status: "healthy",
          available: true,
          version: res.stdout.trim(),
          lastCheckedAt: new Date().toISOString(),
          latencyMs,
          capabilities: {
            formats: ["mp4", "webm", "mkv", "mp3", "m4a", "opus"],
            supportsSubtitles: true,
            supportsAudioExtraction: true,
            supportsBatch: true,
            supportsThumbnails: true,
            maxResolution: "8K",
          },
        };
      }

      return {
        provider: this.name,
        status: "offline",
        available: false,
        lastCheckedAt: new Date().toISOString(),
        latencyMs,
        errorMessage: `yt-dlp returned exit code ${res.exitCode}: ${res.stderr.trim()}`,
        capabilities: {
          formats: [],
          supportsSubtitles: false,
          supportsAudioExtraction: false,
          supportsBatch: false,
          supportsThumbnails: false,
        },
      };
    } catch (err) {
      return {
        provider: this.name,
        status: "offline",
        available: false,
        lastCheckedAt: new Date().toISOString(),
        errorMessage: err instanceof Error ? err.message : String(err),
        capabilities: {
          formats: [],
          supportsSubtitles: false,
          supportsAudioExtraction: false,
          supportsBatch: false,
          supportsThumbnails: false,
        },
      };
    }
  }

  async inspect(request: InspectRequest): Promise<InspectResult> {
    const policy = validateAndNormalizeUrl(request.url);
    const health = await this.healthCheck();
    if (!health.available) {
      throw new MediaError(
        "MEDIA_PROVIDER_OFFLINE",
        "yt-dlp binary is not available or not installed on this machine.",
        true,
      );
    }

    const res = await runProcessSafely({
      binary: this.binaryName,
      args: ["--dump-json", "--no-warnings", "--no-call-home", policy.normalizedUrl],
      timeoutMs: 30_000,
    });

    if (res.exitCode !== 0) {
      throw new MediaError(
        "MEDIA_PROVIDER_ERROR",
        `yt-dlp inspect failed: ${res.stderr || res.stdout}`,
        false,
        { exitCode: res.exitCode },
      );
    }

    try {
      const data = JSON.parse(res.stdout);
      const formats: MediaFormat[] = Array.isArray(data.formats)
        ? data.formats.map((f: any) => ({
            formatId: String(f.format_id || f.format),
            ext: f.ext || "mp4",
            resolution: f.resolution || `${f.width || "?"}x${f.height || "?"}`,
            width: f.width,
            height: f.height,
            filesizeApprox: f.filesize_approx || f.filesize,
            fps: f.fps,
            vcodec: f.vcodec,
            acodec: f.acodec,
            qualityNote: f.format_note,
          }))
        : [];

      const subtitles: MediaSubtitle[] = [];
      if (data.subtitles && typeof data.subtitles === "object") {
        for (const [lang, subList] of Object.entries(data.subtitles)) {
          if (Array.isArray(subList) && subList[0]) {
            subtitles.push({
              language: lang,
              ext: (subList[0] as any).ext || "vtt",
              url: (subList[0] as any).url,
              isAutoGenerated: false,
            });
          }
        }
      }

      return {
        provider: this.name,
        url: request.url,
        normalizedUrl: policy.normalizedUrl,
        title: data.title || "Untitled Media",
        description: data.description,
        mediaType: data.vcodec && data.vcodec !== "none" ? "video" : "audio",
        durationSec: data.duration,
        thumbnailUrl: data.thumbnail,
        formats,
        subtitles,
        author: data.uploader || data.channel,
        sourcePlatform: policy.platform,
        requiresAuth: false,
        supported: true,
        inspectedAt: new Date().toISOString(),
      };
    } catch {
      return {
        provider: this.name,
        url: request.url,
        normalizedUrl: policy.normalizedUrl,
        title: `${policy.platform.toUpperCase()} Item`,
        mediaType: "video",
        formats: [{ formatId: "best", ext: "mp4" }],
        subtitles: [],
        sourcePlatform: policy.platform,
        requiresAuth: false,
        supported: true,
        inspectedAt: new Date().toISOString(),
      };
    }
  }

  async download(
    job: MediaJob,
    onProgress?: (progress: Partial<MediaJob>) => void,
  ): Promise<{ outputPath: string; metadata?: Record<string, unknown> }> {
    const policy = validateAndNormalizeUrl(job.sourceUrl);
    const health = await this.healthCheck();
    if (!health.available) {
      throw new MediaError(
        "MEDIA_PROVIDER_OFFLINE",
        "yt-dlp binary is not available or not installed on this machine.",
        true,
      );
    }

    const targetOutput = job.outputPath;
    if (!targetOutput) {
      throw new MediaError("MEDIA_INVALID_ARGUMENT", "Job outputPath is missing.");
    }

    const args = ["-o", targetOutput, "--no-part", "--no-warnings", policy.normalizedUrl];
    if (job.preset === "audio") {
      args.unshift("-x", "--audio-format", "mp3");
    }

    const res = await runProcessSafely({
      binary: this.binaryName,
      args,
      timeoutMs: 300_000,
      onStdoutLine: (line) => {
        const match = line.match(/\[download\]\s+(\d+(?:\.\d+)?)%/);
        if (match && onProgress) {
          const pct = Math.min(100, Math.max(0, parseFloat(match[1])));
          onProgress({ progressPercent: pct });
        }
      },
    });

    if (res.exitCode !== 0) {
      throw new MediaError(
        "MEDIA_DOWNLOAD_FAILED",
        `yt-dlp download failed (exit ${res.exitCode}): ${res.stderr || res.stdout}`,
        false,
        { exitCode: res.exitCode },
      );
    }

    return { outputPath: targetOutput };
  }

  async cancel(jobId: string): Promise<void> {
    const active = this.activeJobs.get(jobId);
    if (active) {
      active.abort();
      this.activeJobs.delete(jobId);
    }
  }

  async getStatus(jobId: string): Promise<JobStatus> {
    return this.activeJobs.has(jobId) ? "running" : "completed";
  }
}
