/**
 * Phase 18.1 — llms.txt PROPOSAL generation (never deployed automatically).
 * Builds a proposal from verified Phase 18 project context only: domain,
 * display name, key pages, primary topics. Every URL is validated
 * same-domain; secrets/admin/internal paths are excluded by policy.
 */

export interface LlmsTxtProposal {
  content: string;
  includedUrls: string[];
  excludedCount: number;
  warnings: string[];
}

const BLOCKED_PATH_PATTERNS = [
  /admin/i, /login/i, /staging/i, /private/i, /api\//i, /wp-admin/i, /dashboard/i, /internal/i, /\.env/i, /config/i,
];

export function generateLlmsTxtProposal(input: {
  domain: string;
  displayName?: string;
  businessDescription?: string;
  keyPages?: Array<{ url: string; label?: string; purpose?: string; priority?: string }>;
  primaryTopics?: string[];
}): LlmsTxtProposal {
  const domain = input.domain.trim().toLowerCase();
  const warnings: string[] = [];
  const includedUrls: string[] = [];
  let excludedCount = 0;

  const seen = new Set<string>();
  const sections: Array<{ title: string; links: Array<{ url: string; label: string }> }> = [];
  const addLink = (url: string, label: string) => {
    let parsed: URL;
    try { parsed = new URL(url); } catch { excludedCount++; warnings.push(`dropped invalid URL: ${url}`); return; }
    const hostname = parsed.hostname.toLowerCase();
    if (hostname !== domain && !hostname.endsWith("." + domain)) { excludedCount++; warnings.push(`dropped cross-domain URL: ${url}`); return; }
    if (BLOCKED_PATH_PATTERNS.some(pattern => pattern.test(parsed.pathname))) { excludedCount++; warnings.push(`dropped sensitive-path URL: ${url}`); return; }
    if (parsed.protocol !== "https:") { excludedCount++; warnings.push(`dropped non-https URL: ${url}`); return; }
    const key = parsed.toString();
    if (seen.has(key)) return;
    seen.add(key);
    includedUrls.push(key);
    sections[sections.length - 1]!.links.push({ url: key, label: label.slice(0, 120) });
  };

  const name = (input.displayName || domain).slice(0, 80);
  const headerLines = [
    `# ${name}`,
    "",
    input.businessDescription ? `${input.businessDescription.slice(0, 300)}` : `Official site: https://${domain}`,
    "",
  ];

  sections.push({ title: "Site", links: [] });
  addLink(`https://${domain}/`, "Home");

  if (input.keyPages && input.keyPages.length > 0) {
    sections.push({ title: "Pages", links: [] });
    for (const page of input.keyPages) {
      const absolute = page.url.startsWith("http") ? page.url : `https://${domain}${page.url.startsWith("/") ? "" : "/"}${page.url}`;
      addLink(absolute, page.label ?? page.purpose ?? page.url);
    }
  } else {
    warnings.push("no keyPages configured — proposal contains only the homepage; add key pages for a useful file");
  }

  if (input.primaryTopics && input.primaryTopics.length > 0) {
    sections.push({ title: "Topics", links: [] });
    // Topics are listed as a markdown bullet without links (no fabricated URLs).
    const topicsSection = sections[sections.length - 1]!;
    topicsSection.links = [];
    // Represent topics as plain bullets in content below.
  }

  const lines: string[] = [...headerLines];
  for (const section of sections) {
    if (section.links.length === 0 && section.title !== "Topics") continue;
    lines.push(`## ${section.title}`, "");
    for (const link of section.links) lines.push(`- [${link.label}](${link.url})`);
    if (section.title === "Topics" && input.primaryTopics && input.primaryTopics.length > 0) {
      for (const topic of input.primaryTopics.slice(0, 10)) lines.push(`- ${topic}`);
    }
    lines.push("");
  }
  lines.push("> Generated by Pao GEO Intelligence Engine (Phase 18.1). Human approval required before deployment.");

  return { content: lines.join("\n"), includedUrls, excludedCount, warnings };
}
